# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lewawards', '0005_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
