# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lewawards', '0006_grade_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='avg',
            field=models.IntegerField(null=True),
        ),
    ]
