# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lewawards', '0007_grade_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='overall_grade',
            field=models.IntegerField(null=True),
        ),
    ]
