# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lewawards', '0010_auto_20190329_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
